missing_persons/apps/dashboard/urls.py
from django.urls import include, path

app_name = "dashboard"

urlpatterns = [
    path("", include("missing_persons.apps.dashboard.routes.index")),
    # user urls
    path("users/", include("missing_persons.apps.dashboard.routes.login"))

]

missing_persons/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    # dashboard routes
    path("dashboard/", include("dashboard.urls")),
    # allauth routes
    path("accounts/", include("allauth.urls")),
    path(
        "",
        LoginView.as_view(
            template_name="account/login.html", redirect_authenticated_user=True
        ),
        name="login",
    ),
    path(
        "auth/logout/",
        LogoutView.as_view(template_name="account/logout.html"),
        name="logout",
    ),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

missing_persons/apps/dashboard/models.py
# Create your models here.

missing_persons/apps/login/models.py
import uuid

from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from phonenumber_field.modelfields import PhoneNumberField
from simple_history.models import HistoricalRecords

from .managers import CustomUserManager


# Create your models here.
class UserAccount(AbstractUser):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    phone_number = PhoneNumberField(null=True, blank=True)
    bio = models.TextField(verbose_name=_("Bio"), blank=True, null=True)
    history = HistoricalRecords()
    email = models.EmailField(_("Email address"), unique=True)
    username = None
    
    USERNAME_FIELD = "email"
    

    REQUIRED_FIELDS = [
        "first_name",
        "last_name",
    ]

    objects = CustomUserManager()



    class Meta:
        verbose_name = _("User Account")
        verbose_name_plural = _("User Accounts")
        ordering = ("-date_joined",)

    def __str__(self) -> str:
        return self.get_full_name()

    def get_absolute_url(self):
        return reverse("dashboard:login:staff_details", kwargs={"pk": self.pk})

missing_persons/apps/dashboard/routes/index.py
from django.urls import path

from ..views import IndexTemplateView

urlpatterns = [
    path("", IndexTemplateView.as_view(), name="home_page"),
]

missing_persons/apps/dashboard/routes/login.py
from django.urls import path

from ..views import (
    StaffCreateTemplateView,
    StaffDetailTemplateView,
    StaffListTemplateView,
    StaffUpdateTemplateView,
)

app_name = "login"

urlpatterns = [
    path("staff/", StaffListTemplateView.as_view(), name="staff_list"),
    path("staff/new/", StaffCreateTemplateView.as_view(), name="staff_create"),
    path("staff/<uuid:pk>/", StaffDetailTemplateView.as_view(), name="staff_details"),
    path(
        "staff/edit/<uuid:pk>/",
        StaffUpdateTemplateView.as_view(),
        name="staff_update",
    ),
]

missing_persons/apps/dashboard/views/index.py
from django.views.generic import TemplateView

from mixins.dashboard import AdminDashBoardMixin


# index page controller
class IndexTemplateView(AdminDashBoardMixin, TemplateView):
    template_name = "index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

missing_persons/apps/login/views.py
# Create your views here.

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Mosaddek">

    <link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}">
    <title>{% block title %} {%endblock %} Dashboard | {{ site.name }} </title>
    <link href="//fonts.googleapis.com/css?family=Montserrat:300,400,500,600,700,800" rel="stylesheet">
    <link href="//fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
          integrity="sha256-eZrrJcwDc/3uDhsdt61sL2oOBY362qM3lon1gyExkL0=" crossorigin="anonymous" />
    <link href="{% static 'vendor/dashlab-icon/dashlab-icon.css' %}" rel="stylesheet" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.5.5/css/simple-line-icons.min.css"
          integrity="sha512-QKC1UZ/ZHNgFzVKSAhV5v5j73eeL9EEN289eKAEFaAjgAiobVAnVv/AGuPbXsKl1dNoel3kNr6PYnSiTzVVBCw=="
          crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/themify-icons/0.1.2/css/themify-icons.css">
    <link href="{% static 'vendor/weather-icons/css/weather-icons.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/jquery-ui/jquery-ui.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/icheck/skins/all.css' %}" rel="stylesheet">
    <style>
        .breadcrumb a  {
            color: var(--brand-red) !important;
        }
    </style>
    {% block styles %}{% endblock %}
    <link href="{% static 'css/main.css' %}" rel="stylesheet">
</head>

<body class="left-sidebar-fixed">
{% include 'header.html' %}

<div class="app-body">
    {% include 'side-nav.html' %}

    <div class="content-wrapper">
        <div class="container-fluid">
            {% block content %}{% endblock %}
        </div>

        <footer class="sticky-footer">
            <div class="container">
                <div class="text-center">
                    <small>Copyright &copy; Insight {% now 'Y' %}</small>
                </div>
            </div>
        </footer>
    </div>
</div>

<!--basic scripts-->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/jquery-ui/jquery-ui.min.js' %}"></script>
{% comment %} <script src="{% static 'vendor/popper.min.js' %}"></script> {% endcomment %}
<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'vendor/jquery.dcjqaccordion.2.7.js' %}"></script>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

{% block scripts %}{% endblock %}


<!--[if lt IE 9]>
    <script src="{% static 'vendor/modernizr.js' %}"></script>
    <![endif]-->

<!--basic scripts initialization-->
<script src="{% static 'js/scripts.js' %}"></script>
<script>
    $(document).ready(function () {
        setInterval(() => {
            $("#clock").html(new Date().toLocaleTimeString());
        }, 1000);
    })
    {% if messages %}
    {% for message in messages %}
    $(document).ready(function(){
        swal({
            title: "{{ message }}",
            icon: "{{ message.tags }}",
            timer: 2000,
            });
    });
    {% endfor %}
    {% endif %}
</script>
</body>
</html>

templates/confirm-delete.html
{% extends 'base.html' %}

{% block title %}
    Confirm Delete
{% endblock %}


{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="card shadow-sm">
                <div class="card-body">
                    <h3 class="text-center py-3">Delete</h3>
                    <div class="col-md-6 mx-auto">
                        <form method="post" enctype="multipart/form-data">
                            {%csrf_token%}
                            <div class="py-3 text-center">
                                <p> Proceed with Delete? </p>
                                <button class="btn btn-danger">Delete</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

templates/dashboard/login/staff/detail.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}

{% block title %}
staff Details - {{ staff.get_full_name }}
{% endblock %}


{% block content %}
<nav aria-label="breadcrumb mb-2">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'dashboard:home_page' %}">{{ site.name }}</a></li>
      <li class="breadcrumb-item"><a href="{% url 'dashboard:login:staff_list' %}">Staff</a></li>
      <li class="breadcrumb-item active" aria-current="page">{{ staff.get_full_name }}</li>
    </ol>
</nav>

<div class="row mb-4">
    <div class="col-md-12">
        <div class="card shadow-sm rounded-border">
            <div class="card-body">
                <h5 class="text-center py-4"> {{ staff.get_full_name }} </h5>
                <div class="row">
                    <div class="col-md-4 text-center">
                        <img src="{% static 'img/progress.svg' %}" class="card-img-top" class="w-75">
                        <div class="py-3">
                            <a href="{% url 'dashboard:login:staff_update' pk=staff.pk %}">
                                <button class="btn btn-brand text-white btn-sm mx-1">Edit</button>
                            </a>
                        </div>
                    </div>
                    <div class="table-responsive col-md-8 shadow-sm">
                        <table class="table table-striped">
                            <tbody>
                                <tr>
                                    <th>Full Names</th>
                                    <td>{{ staff.get_full_name }}</td>
                                </tr>
                                <tr>
                                    <th>Contact</th>
                                    {% if staff.phone_number %}
                                    <td> {{staff.phone_number }} </td>
                                    {% else %}
                                    <td><span class="badge badge-pill badge-info">Not provided</span></td>
                                    {% endif %}
                                </tr>
                                <tr>
                                    <th>Email</th>
                                    <td>{{ staff.email }}</td>
                                </tr>
                                <tr>
                                    <th>Role</th>
                                    <td>{{ staff.role }}</td>
                                </tr>
                                <tr>
                                    <th>Status</th>
                                    {% if staff.is_active  %}
                                    <td> <span class="badge badge-pill badge-success">Active</span> </td>
                                    {% else %}
                                    <td><span class="badge badge-pill badge-danger">Inactive</span></td>
                                    {% endif %}
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>

  <!-- activities list -->
  <div class="row mb-1">
    <div class="col-md-12">
        <div class="card shadow-sm rounded-border">
            <div class="card-body">
                <h5 class="text-center py-3 weight-600">Activity name</h5>
                <div class="table-responsive table-responsive-sm">
                    <div class="table-responsive table-responsive-sm">
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th>Name</th>
                                    <th>Added by</th>
                                    <th>Price</th>
                                    <th>Added at</th>
                                    <th>Status</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for activity in activities %}
                                <tr>
                                    <td>{{activity.name}}</td>
                                    <td>{{activity.added_by.get_full_name}}</td>
                                    <td>{{ property.location }}</td>
                                    <td>{{activity.price | intcomma }}</td>
                                    <td>{{activity.created | timesince }}</td>
                                    {% if property.status == 'lease' %}
                                    <td><span class="badge badge-warning">Leased</span></td>
                                    {% elif property.status == 'for sale' %}
                                    <td><span class="badge badge-info">For Sale</span></td>
                                    {% else %}
                                    <td><span class="badge badge-success">Sold</span></td>
                                    {% endif%}
                                    <td>
                                        <a class="btn btn-brand btn-sm text-white"
                                            href="">View</a>
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- end activities list -->

{% endblock %}

templates/dashboard/login/staff/form.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
{% if '/staff/registration/' in request.path %}
Add Staff
{% elif '/staff/edit/' in request.path %}
Edit Staff
{% endif %}
{% endblock %}

{% block styles %}
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/jquery-ui/jquery-ui.min.js' %}"></script>
<script src="{% static 'vendor/popper.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'vendor/jquery.dcjqaccordion.2.7.js' %}"></script>
<style>
    .calendar>table>caption {
        caption-side: unset;
    }
</style>
{% endblock styles %}

{% block content %}
<nav aria-label="breadcrumb mb-2">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'dashboard:home_page' %}">{{site.name}}</a></li>
      <li class="breadcrumb-item"><a href="{% url 'dashboard:login:staff_list' %}">Staff</a></li>
      <li class="breadcrumb-item active" aria-current="page">
          {% if 'edit' in request.path %}
          Edit
          {% else %} Add
         {% endif %}
         Staff</li>
    </ol>
</nav>

    <div class="row">
        <div class="col-md-12">
            <div class="card shadow-sm rounded-border">
                <div class="card-body">
                    {% if '/staff/new/' in request.path %}
                    <h4 class="text-center py-3">Add Staff</h4>
                    {% elif '/staff/edit/' in request.path %}
                    <h4 class="text-center py-3">Edit Staff</h4>
                    {% endif %}
                    <div class="col-md-10 mx-auto">
                        <form method="post" enctype="multipart/form-data">
                            {%csrf_token%}
                            {% include 'partials/form-half.html' %}
                            {{ form.media }}
                            <div class="py-3 text-center">
                                {% if '/staff/new/' in request.path %}
                                <button class="btn btn-primary">Add Staff</button>
                                {% elif '/staff/edit/' in request.path %}
                                <button class="btn btn-primary">Edit Staff</button>
                                {% endif %}
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

{% comment %}{% block scripts %}
<script src="http://code.jquery.com/ui/1.10.2/jquery-ui.min.js" type="text/javascript"></script>
<script type="text/javascript" src="//netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
{% endblock scripts %}{% endcomment %}

templates/dashboard/login/staff/list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
staff
{% endblock %}

{% block styles %}
<link href="{% static 'vendor/data-tables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}

<nav aria-label="breadcrumb mb-2">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'dashboard:home_page' %}">{{ site.name }}</a></li>
      <li class="breadcrumb-item active" aria-current="page">Staff</li>
    </ol>
</nav>

<div class="row">
    <div class="col-md-12">
        <div class="card shadow-sm rounded-border">
            <div class="card-body">
                <h3 class="text-center py-3">Recently Added staff</h3>
                <div class="float-right">
                    <a href="{% url 'dashboard:login:staff_create' %}">
                        <button class="btn btn-brand text-white btn-sm mb-2">Add staff</button>
                    </a>
                </div>
                <div class="table-responsive table-responsive-sm">
                    <table class="table table-striped" id="data-table">
                        <thead>
                            <tr>
                                <th>Staff ID</th>
                                <th>Staff Name</th>
                                <th>Staff Email</th>
                                <th>Staff Phone Number</th>
                                <th>Joined</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for staff in staffs %}
                            <tr>
                                <td>#{{staff.id}}</td>
                                <td>{{staff.get_full_name}}</td>
                                <td>{{staff.email}}</td>
                                <td>{{staff.phone_number}}</td>
                                <td>{{staff.date_joined | timesince}} ago</td>
                                <td>
                                    <a class="text-brand"
                                        href="{{ staff.get_absolute_url }}">View</a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script src="{% static 'vendor/data-tables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'vendor/data-tables/dataTables.bootstrap4.min.js' %}"></script>
<script>
    $('#data-table').DataTable({
        "order": []
    });
</script>
{% endblock %}

templates/header.html
{% load static %}

<header class="app-header">
    <div class="branding-wrap">
        <a href="#" class="nav-link mt-2 float-left js_left-nav-toggler pos-fixed">
            <i class="ti-align-right"></i>
        </a>
        <div class="navbar-brand pos-fixed">
            <a class="" href="/">
                <img src="{% static 'img/logo.svg' %}" style="height:2em;" alt="{{ site.name}} logo" id="logo">
            </a>
        </div>
    </div>

    <ul class="header-links hide-arrow navbar p-3">
        <li class="nav-item sm-device-none pt-2" style="padding-right: 7rem;">
            <h4 class="text-center">{{ site.name }} - Data Management System</h4>
        </li>
        <li class="nav-item sm-device-none mr-3">
            <i class="fa fa-clock-o"></i> <span id="clock">Loading...</span>
        </li>
        <li class="nav-item sm-device-none mr-3">
            <i class="fa fa-user"></i> {{ request.user.get_full_name }}
        </li>
        <li class="nav-item sm-device-none">
            <form method="post" action="{% url 'logout' %}">
            {% csrf_token %}
            <button class="btn btn-sm btn-brand text-white" type="submit">
                <i class="fa fa-sign-out"></i> Logout
            </button>
            </form>
        </li>
    </ul>
</header>

templates/index.html
{% extends 'base.html' %}
{% load humanize %}


{% block content %}
<nav aria-label="breadcrumb mb-2">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="">{{ site.name }}</a></li>
        <li class="breadcrumb-item active" aria-current="page">Dashboard</li>
    </ol>
</nav>

<div class="row">
    <div class="col-xl-3 col-sm-6">
        <div class="card mb-4 bg-white rounded-border">
            <div class="card-body">
                <div class="media d-flex align-items-center">
                    <div class="mr-4 rounded-circle bg-brand sr-icon-box text-white">
                        <i class="ti-search"></i>
                    </div>
                    <div class="media-body text-dark">
                        <h4 class="text-uppercase mb-0 weight-500">1</h4>
                        <span>Placeholder analytics 1</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xl-3 col-sm-6">
        <div class="card mb-4 bg-white rounded-border">
            <div class="card-body">
                <div class="media d-flex align-items-center">
                    <div class="mr-4 rounded-circle bg-brand sr-icon-box text-white">
                        <i class="ti-home"></i>
                    </div>
                    <div class="media-body text-dark">
                        <h4 class="text-uppercase mb-0 weight-500">2</h4>
                        <span>Placeholder analytics 2</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xl-3 col-sm-6">
        <div class="card mb-4 bg-white rounded-border">
            <div class="card-body">
                <div class="media d-flex align-items-center ">
                    <div class="mr-4 rounded-circle bg-brand sr-icon-box text-white">
                        <i class="ti-user"></i>
                    </div>
                    <div class="media-body text-dark">
                        <h4 class="text-uppercase mb-0 weight-600">3 </h4>
                        <span>Placeholder analytics 3</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xl-3 col-sm-6">
        <div class="card mb-4 bg-white rounded-border">
            <div class="card-body">
                <div class="media d-flex align-items-center">
                    <div class="mr-4 rounded-circle bg-brand  sr-icon-box text-white">
                        <i class="ti-location-arrow"></i>
                    </div>
                    <div class="media-body text-dark">
                        <h4 class="text-uppercase mb-0 weight-600">4</h4>
                        <span>Placeholder analytics 4</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="card shadow-sm mb-3 rounded-border">
            <div class="card-body justify-content-center">
                <h3 class="text-center py-3 weight-600">Recently Listed Items</h3>
                <div class="table-responsive table-responsive-sm">
                    <table class="table table-striped">
                        <thead>
                        <tr>
                            <th>Name</th>
                            <th>Added by</th>
                            <th>Location</th>
                            <th>Price</th>
                            <th>Added at</th>
                            <th>Status</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for item in items %}
                        <tr>
                            <td>{{item.name}}</td>
                            <td>{{item.added_by.get_full_name}}</td>
                            <td>{{ item.location }}</td>
                            <td>{{item.price | intcomma }}</td>
                            <td>{{item.created | timesince }}</td>
                            {% if item.status == 'lease' %}
                            <td><span class="badge badge-warning">Leased</span></td>
                            {% elif item.status == 'for sale' %}
                            <td><span class="badge badge-info">For Sale</span></td>
                            {% else %}
                            <td><span class="badge badge-success">Sold</span></td>
                            {% endif%}
                            <td>
                                <a class="text-brand"
                                   href="">View</a>
                            </td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/side-nav.html
<div class="left-nav-wrap custom-left-nav-wrap">
  <div class="left-sidebar">
      <nav class="sidebar-menu side-nav-menu custom-sidebar-menu">
          <ul id="nav-accordion">
              <li class="sub-menu">
                  <a href="{% url 'dashboard:home_page' %}" class="{% if request.path == '/' %}active{% endif %}">
                      <i class="ti-dashboard"></i>
                      <span>Dashboard</span>
                  </a>
              </li>
              <li class="sub-menu">
                  <a href="#" class="{% if '/properties/' in request.path %}active{% endif %}">
                      <i class="icon-basket-loaded"></i>
                      <span>Menu with sub items</span>
                  </a>
                  <ul class="sub">
                      <li class="#">
                          <a href="">Sub Item 1</a>
                      </li>
                  </ul>
                <ul class="sub">
                      <li class="#">
                          <a href="">Sub Item two</a>
                      </li>
                  </ul>
              </li>
              <li class="sub-menu">
                <a href=""
                    class="{% if '/property-enquiries/' in request.path %}active{% endif %}">
                    <i class="ti-write"></i>
                    <span>Enquiries</span>
                </a>
            </li>
              <li class="sub-menu">
                <a href=""
                    class="{% if '/listing-requests/' in request.path %}active{% endif %}">
                    <i class="ti-ink-pen"></i>
                    <span>Menu Without Sub Items 1</span>
                </a>
            </li>
              <li class="sub-menu">
                <a href=""
                    class="{% if '/features/' in request.path %}active{% endif %}">
                    <i class="ti-bookmark-alt"></i>
                    <span>Menu Without Sub Items 1</span>
                </a>
            </li>

            {% if request.user.is_superuser or request.user.role == 'Admin' %}

            {% comment %}
            <li class="sub-menu">
                <a href="#" class="{% if 'careers' in request.path %}active{% endif %}">
                    <i class="ti-agenda"></i>
                    <span>Careers and Tenders</span>
                </a>
                <ul class="sub">
                    <li class="{% if 'careers' in request.path %}active{% endif %}">
                        <a href="{% url 'core:dashboard:careers:careers_list' %}">Careers</a>
                    </li>
                    <li class="{% if 'tenders' in request.path %}active{% endif %}">
                        <a href="{% url 'core:dashboard:tenders:tenders_list' %}">Tenders</a>
                    </li>
                </ul>
            </li>
            {% endcomment %}
              <li class="sub-menu">
                  <a href="" class="{% if 'about-us' in request.path == '/' %}active{% endif %}">
                      <i class="ti-info"></i>
                      <span>About</span>
                  </a>
              </li>
              {% comment %}
              <li class="sub-menu">
                  <a href="" class="{% if 'news-letter' in request.path == '/' %}active{% endif %}">
                      <i class="fa fa-folder-open"></i>
                      <span>Mailing List</span>
                  </a>
              </li>
              {% endcomment %}
              <li class="sub-menu">
                <a href="#" class="{% if 'users' in request.path %}active{% endif %}">
                    <i class="ti-settings"></i>
                    <span>System Admin</span>
                </a>
                <ul class="sub">
                    <li class="{% if 'staff' in request.path %}active{% endif %}">
                        <a href="{% url 'dashboard:login:staff_list' %}">All Staff</a>
                    </li>
                    <li class="{% if request.path == '/staff/new/' %}active{% endif %}">
                        <a href="{% url 'dashboard:login:staff_create' %}">Add Staff</a>
                    </li>
                </ul>
            </li>
              {% endif %}
              {% comment %}
              <li class="sub-menu">
                <a
                  href="#"
                  class="{% if 'accounts/' in request.path %}active{% endif %}"
                >
                  <i class="ti-info"></i>
                  <span>Account</span>
                </a>
                <ul class="sub">
                  <li
                    class="{% if 'accounts/password-change/' in request.path %}active{% endif %}"
                  >
                    <a href="{% url 'password_update' %}">Password Reset</a>
                  </li>
                </ul>
              </li>
              {% endcomment %}
          </ul>
      </nav>
  </div>
</div>